### ISSUE TITLE
Artifacts not extracting for my game

### ISSUE THREAD

**Issue by W1TBL1TZ** [Da-Teach/RaidExtractor#12]
I am running 2 instances of the game, and the artifacts are not being extracted for one of them. Below is the entire section for artifacts. Also, is there a way to contact you via discord or something? I was busy writing something nearly identical to your optimizer, so I would like to collaborate.

"artifacts": [
    {
      "id": 0,
      "sellPrice": 0,
      "price": 0,
      "level": 0,
      "isActivated": false,
      "kind": "UnknownArtifact",
      "rank": "Unknown",
      "rarity": "Unknown",
      "setKind": "None",
      "isSeen": false,
      "failedUpgrades": 0,
      "primaryBonus": {
        "kind": "0",
        "isAbsolute": false,
        "value": 0.0,
        "enhancement": 0.0,
        "level": 0
      },
      "secondaryBonuses": []
    }
  ]

**Comment by justuscook** [comment]
I second both aspects of the issue lol.  I have used it in the past to great success.  I am also interested in basically extracting the index info for all champs, which static_data is pretty good for.  I would also love to chat via discord if your there.  Keep up the good work!

**Comment by Da-Teach** [comment]
So to sum up the issue, you have two computers each running their own Raid, one works and the other doesn't?  And both are (according to the plarium launcher) running v0.226?  But heroes, are they working/exported?   Or is it on the same computer where you log out one account and login to another account?

It seems like a memory variable that should be initialized isn't, haven't encountered it before but I guess it can happen.  Did you try going to the artifacts list in the game on the account that has this issue?

**Comment by W1TBL1TZ** [comment]
One computer, running 2 instances. Both instances the same version, v226. One running in regular plarium play, the other running plarium play inside sandboxie. 

Heroes export works fine and has all of the champs as well as their equiped artifact ids.

Currently, I am only running the regular plarium play with my own account, and it is not working. I do not even have a 2nd instance opened

**Comment by ansekh** [comment]
Hello,

Same problem for me.

0 artefact in website

**Comment by justuscook** [comment]
My issue is that no artifacts load for me, using only one account here.

**Comment by Da-Teach** [comment]
Found the issue, they changed the way they store artifacts in memory. This update should solve that problem.

**Comment by IamBeardo** [comment]
> Found the issue, they changed the way they store artifacts in memory. This update should solve that problem. Let me know if it's been properly resolved, I did check a few artifacts and they all seemed ok.


I had the same issue - the new update solwed that - thanks!
