### ISSUE TITLE
0.3 returns JSON only with artifacts

### ISSUE THREAD

**Issue by theinfra** [Da-Teach/RaidExtractor#2]
I downloaded 0.3 release and extracted to a new folder, executed and got the new WinForm which indicates I'm truly in 0.3. But pressing the button and saving the file even to a new one only returns the Artifacts dict, there's no hero data. It's even in the previous format because the dump should be a dict of [Artifacts, Heroes] but the data written to the file is just the Artifacts data directly without it being in its specific key

**Comment by Da-Teach** [comment]
I didn't build the version with hero's. Without a static data dump the hero info is not very usefull. The stats for each hero are in static data and the hero has an id liking to that data.

**Comment by Da-Teach** [comment]
v0.4 includes hero information :)
