### ISSUE TITLE
Update 2.2 Compatibility

### ISSUE THREAD

**Issue by Paumedie** [Da-Teach/RaidExtractor#3]
The latest update to the Plarium Play version seems to have broken the extractor.  Love the tool!

**Comment by mjovita** [comment]
I love using this. I hope it gets updated to Raid's current version. 

Thank You.

**Comment by Da-Teach** [comment]
Just updated to v2.2 (see release v0.6). Fun fact, they added a few heroes :)

**Comment by Paumedie** [comment]
@Da-Teach I think the new release might have your localhost hardcoded for the "View on Website" function.  I'm getting this error: 
![image](https://user-images.githubusercontent.com/71401440/93380165-7b568400-f824-11ea-9fee-9fc25b71aa16.png)

**Comment by Da-Teach** [comment]
> @Da-Teach I think the new release might have your localhost hardcoded for the "View on Website" function. I'm getting this error:
> ![image](https://user-images.githubusercontent.com/71401440/93380165-7b568400-f824-11ea-9fee-9fc25b71aa16.png)

Download the 0.6.1 zip file from the releases page (it's still listed under 0.6). I accidentally forgot to remove the debug-url.

**Comment by Paumedie** [comment]
Thanks!
