### ISSUE TITLE
Implement stat multiplier formula

### ISSUE THREAD

**Issue by Rodze** [Da-Teach/RaidExtractor#7]
You say there's an issue with stats by a few points.  I've seen your multipliers, but I don't now how you got them.

In any case you're not using it, the game formula for health/atk/def is:

`round( baseStat * multiplier1 * (multiplier2 ^ ( [level - 1] / [10 * grade - 1] ) ) ) (* 15 if health)`

multiplier1 and multiplier2 come from table for each grade:

grade | multiplier1 | multiplier2
--|--|--
2 | 1,600000023841858 | 1,899999976158142
3 | 2,431999921798706 | 1,799999952316284
4 | 3,502079963684082 | 1,700000047683716
5 | 4,762828826904297 | 1,700000047683716
6 | 6,477447032928467 | 1,700000047683716

I built this table debugging the class SharedModel.Meta.Heroes.BattleStats, during the CalcValue method.

IDA gave me the values (because I don't know how to dump directly from memory like you do), so I'm not sure if they are precisely these numbers with these decimal cases. But they've worked from what I tested.

**Comment by Da-Teach** [comment]
Thanks! I'll test them. When I made the dump of static data I found a nicer way of dumping data from the game, so I'll see if I can get the 'Fixed' values from the game. 

I got the multipliers by running the CalcValue method inside the game with level 1 for each grade, but if I look at your formula I can see why it wasn't completely right and caused the discrepancy.
